### ISSUE TITLE
Actif/Passif

### ISSUE THREAD

**Issue by pasmax2** [ts-x/TSX-WEB#124]
## TODO
- [x] - Mise en page et correction
- [x] - Faire la création des list descriptif de Passif/Actif

En actif vous pouvez :
- Avoir accès au radar gratuitement
- augmenté votre vitalité passivement,  il vous suffit de ne pas être
afk.
- Avoir les bonus job
- Gagné 2$ par 19,5 seconde avec les machines
- Être tué

En Passif :
- N'avez pas accès au radar gratuitement
- Votre vitalité ne sera pas augmenté
- Pas d'accès au bonnus job
- Vous gagné 1$ par 19,5 seconde avec les machines
- Vous ne pouvez être tué exeption: Contrat Mercenaire et ce faire écrasé par une voiture

Note à moi même
> Actif
> Avantage MiniMaps tu peu tué qui tu veux qui son en actif la vita monte et bonus de ton job Machine à faut billet font 2$ 19.5seconde
> 
> 
> Passif
> Avantage : Meurt pas
> Meurt avec contrat et sur la route si écrasé avec voiture
> Inconvénient Pas de bonus job et la vitalité ne monte pas et pas de mini map Machine à faut billet font 1$ 19.5seconde

**Comment by messoremTsX** [comment]
Pas besoin de tableaux,  tu peux faire une liste style :

En actif vous pourvez :
<ul>
  <li> avoir accès au radar gratuitement</li>
  <li> augmenté votre vitalité passivement,  il vous suffit de ne pas être
afk.  </li>
</ul>

Le 22 nov. 2016 07:07, "DJBlack Phoénix" <notifications@github.com> a
écrit :

TODO

   - - Mise en page
   - - Faire des phrase explicatif et détailler
   - - Faire la création des tableaux

Fonction Aventage Inconvénient
Actif Vous pouvé tué des personne la vitalité monte + bonus job, accès à la
MiniMaps et les machine à faut billet donne 2$ par 19,5 seconde Vous pouvez
être tué
Pasif Personne peu vous tué mais vous pouvez vous faire écrasé par les
voiture et les mercenaire peuve vous tué en contrat Votalité ne monte pas,
vous n'avez pas acces au bonus job et les machine à faut billet vous donne
1$ par 19,5 seconde

Note à moi même

Actif
Avantage MiniMaps tu peu tué qui tu veux qui son en actif la vita monte et
bonus de ton job Machine à faut billet font 2$ 19.5seconde

Passif
Avantage : Meurt pas
Meurt avec contrat et sur la route si écrasé avec voiture
Inconvénient Pas de bonus job et la vitalité ne monte pas et pas de mini
map Machine à faut billet font 1$ 19.5seconde

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ts-x/TSX-WEB/issues/124>, or mute the thread

**Comment by 0Gentleman** [comment]
Je ferais le correcteur d'orthographe humain après que tu aie fait ta modif ;P

**Comment by pasmax2** [comment]
@messoremTsX : Ses good je vais faire un style liste
@0Gentleman : Ses good je te dis aussitôt que j'ai fini les modif

**Comment by pasmax2** [comment]
@0Gentleman : Ses good tu peu commencé la correction ça me l'aise le temps de modifié mairie.tpl le temps que tu corrigé :+1:

**Comment by pasmax2** [comment]
```
<p>En actif vous pouvez :</p>
<ul>
      <li>Avoir accès au radar gratuitement.</li>
      <li>Augmenté votre vitalité passivement, il vous suffit de ne pas être afk.</li>
      <li>Avoir les bonus job.</li>
      <li>Gagné 2$ par 19,5 seconde avec les machines.</li>
      <li>Être tué.</li>
</ul>
<p>En passif :</p>
<ul>
      <li>N'avez pas accès au radar gratuitement.</li>
      <li>Votre vitalité ne sera pas augmenté.</li>
      <li>Pas d'accès au bonnus job.</li>
      <li>Vous gagné 1$ par 19,5 seconde avec les machines.</li>
      <li>Vous ne pouvez être tué exeption: Contrat Mercenaire et ce faire écrasé par une voiture.</li>
</ul>
```
<p>En actif vous pouvez :</p>
<ul>
      <li>Avoir accès au radar gratuitement.</li>
      <li>Augmenté votre vitalité passivement, il vous suffit de ne pas être afk.</li>
      <li>Avoir les bonus job.</li>
      <li>Gagné 2$ par 19,5 seconde avec les machines.</li>
      <li>Être tué.</li>
</ul>
<p>En passif :</p>
<ul>
      <li>N'avez pas accès au radar gratuitement.</li>
      <li>Votre vitalité ne sera pas augmenté.</li>
      <li>Pas d'accès au bonnus job.</li>
      <li>Vous gagné 1$ par 19,5 seconde avec les machines.</li>
      <li>Vous ne pouvez être tué exeption: Contrat Mercenaire et ce faire écrasé par une voiture.</li>
</ul>
